name: Go Vulnerability Check
on: 
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      report-cc:
        required: false
        type: string
jobs:
  vulnerability-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Run govulncheck
      id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-package: ${{ inputs.package }}
    - name: Send email if vulnerabilities found
      if: steps.govulncheck.outputs.vulnerabilities != ''
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER_ADDRESS }}
        server_port: ${{ secrets.SMTP_SERVER_PORT || 587 }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '[Golang] Vulnerability Report for ${{ github.repository }}'
        body: |
          Hi ${{ github.event.head_commit.author.name }},
          
          The following vulnerabilities were found in your recent commit [https://github.com/${{ github.repository }}/commit/${{ github.sha }}]:
          
          ${{ steps.govulncheck.outputs.vulnerabilities }}
          
          Please address these issues as soon as possible.
        to: ${{ github.event.head_commit.author.email }}
        from: ${{ secrets.SMTP_SENDER_EMAIL }}
        cc: ${{ inputs.report-cc }}